// <auto-generated />
using System;
using CongThongTin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CongThongTin.Data.Migrations
{
    [DbContext(typeof(CongThongTinDbContext))]
    [Migration("20240106192418_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CongThongTin.Data.Entities.ChuongTrinhDaoTaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChuongTrinhDaoTao");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.ChuongTrinhDaoTaoHocPhanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChuongTrinhDaoTaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<Guid>("HocPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChuongTrinhDaoTaoId");

                    b.HasIndex("HocPhanId");

                    b.ToTable("ChuongTrinhDaoTaoHocPhan");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.DiemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<Guid>("HocPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopHocPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SinhVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HocPhanId");

                    b.HasIndex("LopHocPhanId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("Diem");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.DiemRenLuyenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<Guid>("HocKyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HocKyId");

                    b.ToTable("DiemRenLuyen");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.HocKyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HocKy");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.HocPhanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("MaHocPhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HocPhan");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.HocPhiEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaThanhToan")
                        .HasColumnType("bit");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<Guid>("HocKyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HocPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SinhVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HocKyId");

                    b.HasIndex("HocPhanId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("HocPhi");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.KyTucXaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("MaKTX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KyTucXa");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.LichThiEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<Guid>("LopHocPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayThi")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LichThi");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.LopHocPhanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<Guid>("HocKyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HocPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSoHocPhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongSinhVien")
                        .HasColumnType("int");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HocKyId");

                    b.HasIndex("HocPhanId");

                    b.ToTable("LopHocPhan");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.LopHocPhanSinhVienEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<Guid>("LopHocPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SinhVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LopHocPhanId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("LopHocPhanSinhVien");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.NguoiDungEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ChuongTrinhDaoTaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HashMatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSDD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VaiTroId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChuongTrinhDaoTaoId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.PhongEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<Guid>("KTXId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuongSinhVien")
                        .HasColumnType("int");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KTXId");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.PhongSinhVienEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<Guid>("PhongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SinhVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhongId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("PhongSinhVien");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.ThoiGianHocEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<Guid>("GiangVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopHocPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayHoc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("LopHocPhanId");

                    b.ToTable("ThoiKhoaBieu");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.ThongBaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.VaiTroEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.ChuongTrinhDaoTaoHocPhanEntity", b =>
                {
                    b.HasOne("CongThongTin.Data.Entities.ChuongTrinhDaoTaoEntity", "ChuongTrinhDaoTao")
                        .WithMany("ChuongTrinhDaoTaoHocPhanList")
                        .HasForeignKey("ChuongTrinhDaoTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CongThongTin.Data.Entities.HocPhanEntity", "HocPhan")
                        .WithMany("ChuongTrinhDaoTaoHocPhanList")
                        .HasForeignKey("HocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinhDaoTao");

                    b.Navigation("HocPhan");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.DiemEntity", b =>
                {
                    b.HasOne("CongThongTin.Data.Entities.HocPhanEntity", "HocPhan")
                        .WithMany("DiemList")
                        .HasForeignKey("HocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CongThongTin.Data.Entities.LopHocPhanEntity", "LopHocPhan")
                        .WithMany("DiemList")
                        .HasForeignKey("LopHocPhanId")
                        .IsRequired();

                    b.HasOne("CongThongTin.Data.Entities.NguoiDungEntity", "NguoiDung")
                        .WithMany("DiemList")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocPhan");

                    b.Navigation("LopHocPhan");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.DiemRenLuyenEntity", b =>
                {
                    b.HasOne("CongThongTin.Data.Entities.HocKyEntity", "HocKy")
                        .WithMany("DiemRenLuyenList")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocKy");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.HocPhiEntity", b =>
                {
                    b.HasOne("CongThongTin.Data.Entities.HocKyEntity", "HocKy")
                        .WithMany("HocPhiList")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CongThongTin.Data.Entities.HocPhanEntity", "HocPhan")
                        .WithMany("HocPhiList")
                        .HasForeignKey("HocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CongThongTin.Data.Entities.NguoiDungEntity", "NguoiDung")
                        .WithMany("HocPhiList")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("HocPhan");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.LopHocPhanEntity", b =>
                {
                    b.HasOne("CongThongTin.Data.Entities.HocKyEntity", "HocKy")
                        .WithMany("LopHocPhanList")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CongThongTin.Data.Entities.HocPhanEntity", "HocPhan")
                        .WithMany("LopHocPhanList")
                        .HasForeignKey("HocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("HocPhan");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.LopHocPhanSinhVienEntity", b =>
                {
                    b.HasOne("CongThongTin.Data.Entities.LopHocPhanEntity", "LopHocPhan")
                        .WithMany("LopHocPhanSinhVienList")
                        .HasForeignKey("LopHocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CongThongTin.Data.Entities.NguoiDungEntity", "NguoiDung")
                        .WithMany("LopHocPhanSinhVienList")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.NguoiDungEntity", b =>
                {
                    b.HasOne("CongThongTin.Data.Entities.ChuongTrinhDaoTaoEntity", "ChuongTrinhDaoTao")
                        .WithMany("NguoiDungList")
                        .HasForeignKey("ChuongTrinhDaoTaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CongThongTin.Data.Entities.VaiTroEntity", "VaiTro")
                        .WithMany("NguoiDungList")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinhDaoTao");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.PhongEntity", b =>
                {
                    b.HasOne("CongThongTin.Data.Entities.KyTucXaEntity", "KyTucXa")
                        .WithMany("PhongList")
                        .HasForeignKey("KTXId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KyTucXa");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.PhongSinhVienEntity", b =>
                {
                    b.HasOne("CongThongTin.Data.Entities.PhongEntity", "Phong")
                        .WithMany("PhongSinhVienList")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CongThongTin.Data.Entities.NguoiDungEntity", "NguoiDung")
                        .WithMany("PhongSinhVienList")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.ThoiGianHocEntity", b =>
                {
                    b.HasOne("CongThongTin.Data.Entities.NguoiDungEntity", "NguoiDung")
                        .WithMany("ThoiGianHocList")
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CongThongTin.Data.Entities.LopHocPhanEntity", "LopHocPhan")
                        .WithMany("ThoiGianHocList")
                        .HasForeignKey("LopHocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.ThongBaoEntity", b =>
                {
                    b.HasOne("CongThongTin.Data.Entities.NguoiDungEntity", "NguoiDung")
                        .WithMany("ThongBaoList")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.ChuongTrinhDaoTaoEntity", b =>
                {
                    b.Navigation("ChuongTrinhDaoTaoHocPhanList");

                    b.Navigation("NguoiDungList");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.HocKyEntity", b =>
                {
                    b.Navigation("DiemRenLuyenList");

                    b.Navigation("HocPhiList");

                    b.Navigation("LopHocPhanList");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.HocPhanEntity", b =>
                {
                    b.Navigation("ChuongTrinhDaoTaoHocPhanList");

                    b.Navigation("DiemList");

                    b.Navigation("HocPhiList");

                    b.Navigation("LopHocPhanList");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.KyTucXaEntity", b =>
                {
                    b.Navigation("PhongList");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.LopHocPhanEntity", b =>
                {
                    b.Navigation("DiemList");

                    b.Navigation("LopHocPhanSinhVienList");

                    b.Navigation("ThoiGianHocList");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.NguoiDungEntity", b =>
                {
                    b.Navigation("DiemList");

                    b.Navigation("HocPhiList");

                    b.Navigation("LopHocPhanSinhVienList");

                    b.Navigation("PhongSinhVienList");

                    b.Navigation("ThoiGianHocList");

                    b.Navigation("ThongBaoList");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.PhongEntity", b =>
                {
                    b.Navigation("PhongSinhVienList");
                });

            modelBuilder.Entity("CongThongTin.Data.Entities.VaiTroEntity", b =>
                {
                    b.Navigation("NguoiDungList");
                });
#pragma warning restore 612, 618
        }
    }
}
